import { getDB } from "@/lib/db";

type RouteContext = { params: Promise<{ id: string }> };
type CreateBlockBody = { type?: string; variant?: string | null; sort_order?: number; parent_block_id?: string | null; is_visible?: boolean; eyebrow?: string | null; title?: string | null; body?: string | null; media_id?: string | null; gallery_title?: string | null; data?: Record<string, unknown>; after_block_id?: string | null };
type ReorderBody = { block_ids?: string[] };

const DETAIL_TABLES: Record<string, string> = { text: "text_block_data", image: "image_block_data", content: "content_block_data", links: "links_block_data", blog: "blog_block_data", video: "video_block_data", contact: "contact_block_data", social: "social_block_data", others: "others_block_data", flex: "flex_block_data" };
const TEXT_DEFAULTS: Record<string, string> = { "heading-1": "Heading 1", "heading-2": "Heading 2", "heading-3": "Heading 3", wide: "This is a sample wide text. Tell your story with thoughtful words, meaningful details, and the moments that make this story yours.", regular: "This is a sample regular text. Replace this copy with the story, memories, and details you want your readers to discover.", narrow: "This is a sample narrow text. A more intimate reading width works beautifully for personal stories, reflections, and meaningful details." };
const COLUMN_DEFAULTS: Record<string, string[]> = { "columns-2": ["This is the first column. Add your story, a meaningful detail, or a short reflection here.", "This is the second column. Continue the story with another detail, memory, or thought here."], "columns-3": ["First column sample text. Add a short story or detail here.", "Second column sample text. Add another meaningful moment here.", "Third column sample text. Finish this section with another thought here."], "columns-4": ["First column sample text.", "Second column sample text.", "Third column sample text.", "Fourth column sample text."] };

function getTextDefaults(variant: string | null | undefined, body: string | null | undefined, data: Record<string, unknown> | undefined) { if (body) return { body, data }; if (variant && COLUMN_DEFAULTS[variant]) { const columns = COLUMN_DEFAULTS[variant]; return { body: columns.map(text => `<p>${text}</p>`).join(""), data: { ...(data ?? {}), columns: columns.map(text => ({ content: text })) } }; } return { body: TEXT_DEFAULTS[variant ?? ""] ?? "This is sample text. Replace this content with your story.", data }; }
function normalizeImageData(variant: string | null | undefined, data?: Record<string, unknown>) { const current = data ?? {}; return { ...current, collection_id: typeof current.collection_id === "string" ? current.collection_id : null, media_ids: Array.isArray(current.media_ids) ? current.media_ids.filter((id): id is string => typeof id === "string") : [], demo_preview: true, variant: variant ?? "large" }; }
async function createDetailRow(db: ReturnType<typeof getDB>, type: string, blockId: string, body: CreateBlockBody) { const table = DETAIL_TABLES[type]; if (type === "text") return db.prepare(`INSERT INTO ${table} (block_id,content,columns_data) VALUES (?,?,?)`).bind(blockId, body.body ?? "", JSON.stringify(body.data?.columns ?? [])).run(); if (type === "image") return db.prepare(`INSERT INTO ${table} (block_id,layout,caption,alt_text) VALUES (?,?,?,?)`).bind(blockId, String(body.data?.layout ?? body.variant ?? "large"), body.title ?? null, body.data?.alt_text ? String(body.data.alt_text) : null).run(); if (type === "video") return db.prepare(`INSERT INTO ${table} (block_id,provider,video_id,url,settings) VALUES (?,?,?,?,?)`).bind(blockId, body.data?.provider ? String(body.data.provider) : null, body.data?.video_id ? String(body.data.video_id) : null, body.data?.url ? String(body.data.url) : null, JSON.stringify(body.data?.settings ?? {})).run(); return db.prepare(`INSERT INTO ${table} (block_id,content) VALUES (?,?)`).bind(blockId, JSON.stringify(body.data ?? {})).run(); }

export async function GET(_request: Request, { params }: RouteContext) { try { const { id } = await params; const db = getDB(); const result = await db.prepare(`SELECT * FROM story_blocks WHERE story_id=? ORDER BY sort_order ASC`).bind(id).all(); return Response.json({ success: true, blocks: result.results }); } catch (error) { console.error(error); return Response.json({ success: false, error: "Failed to fetch story blocks" }, { status: 500 }); } }

export async function POST(request: Request, { params }: RouteContext) { try { const { id } = await params; const incoming = (await request.json()) as CreateBlockBody; const type = incoming.type; if (!type || !DETAIL_TABLES[type]) return Response.json({ success: false, error: "A supported block type is required" }, { status: 400 }); const db = getDB(); const story = await db.prepare("SELECT id FROM stories WHERE id=? LIMIT 1").bind(id).first(); if (!story) return Response.json({ success: false, error: "Story not found" }, { status: 404 }); const blockId = crypto.randomUUID(); const textDefaults = type === "text" ? getTextDefaults(incoming.variant, incoming.body, incoming.data) : { body: incoming.body ?? null, data: incoming.data }; const imageData = type === "image" ? normalizeImageData(incoming.variant, incoming.data) : textDefaults.data; const body: CreateBlockBody = { ...incoming, type, body: textDefaults.body, data: imageData };
 let sortOrder: number; if (body.sort_order !== undefined) sortOrder = Number(body.sort_order); else if (body.after_block_id) { const current = await db.prepare("SELECT sort_order FROM story_blocks WHERE id=? AND story_id=? LIMIT 1").bind(body.after_block_id, id).first<{ sort_order: number }>(); if (!current) return Response.json({ success: false, error: "Insertion block not found" }, { status: 404 }); const next = await db.prepare("SELECT sort_order FROM story_blocks WHERE story_id=? AND parent_block_id IS NULL AND sort_order>? ORDER BY sort_order ASC LIMIT 1").bind(id, current.sort_order).first<{ sort_order: number }>(); if (next && Number(next.sort_order) - Number(current.sort_order) > 1) sortOrder = Number(current.sort_order) + (Number(next.sort_order) - Number(current.sort_order)) / 2; else { sortOrder = Number(current.sort_order) + 1; await db.prepare("UPDATE story_blocks SET sort_order=sort_order+1 WHERE story_id=? AND parent_block_id IS NULL AND sort_order>=?").bind(id, sortOrder).run(); } } else { const orderRow = await db.prepare("SELECT COALESCE(MAX(sort_order),0)+1000 AS next_order FROM story_blocks WHERE story_id=? AND parent_block_id IS NULL").bind(id).first<{ next_order: number }>(); sortOrder = Number(orderRow?.next_order ?? 1000); }
 await db.prepare(`INSERT INTO story_blocks (id,story_id,type,variant,parent_block_id,is_visible,sort_order,eyebrow,title,body,media_id,gallery_title,data) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(blockId,id,type,body.variant??null,body.parent_block_id??null,body.is_visible===false?0:1,sortOrder,body.eyebrow??null,body.title??null,body.body??null,body.media_id??null,body.gallery_title??null,JSON.stringify(body.data??{})).run(); await createDetailRow(db, type, blockId, body); const block = await db.prepare("SELECT * FROM story_blocks WHERE id=? LIMIT 1").bind(blockId).first(); return Response.json({ success: true, block }); } catch (error) { console.error(error); return Response.json({ success: false, error: "Failed to create story block" }, { status: 500 }); } }

export async function PATCH(request: Request, { params }: RouteContext) { try { const { id } = await params; const body = (await request.json()) as ReorderBody; const blockIds = Array.isArray(body.block_ids) ? body.block_ids.filter(Boolean) : []; if (!blockIds.length) return Response.json({ success: false, error: "block_ids is required" }, { status: 400 }); const db = getDB(); const existing = await db.prepare("SELECT id FROM story_blocks WHERE story_id=? AND parent_block_id IS NULL ORDER BY sort_order ASC").bind(id).all<{ id: string }>(); const existingIds = existing.results.map(block => block.id); if (existingIds.length !== blockIds.length || existingIds.some(blockId => !blockIds.includes(blockId))) return Response.json({ success: false, error: "The supplied block order does not match this story" }, { status: 400 }); for (let index = 0; index < blockIds.length; index += 1) await db.prepare("UPDATE story_blocks SET sort_order=? WHERE id=? AND story_id=? AND parent_block_id IS NULL").bind((index + 1) * 1000, blockIds[index], id).run(); const result = await db.prepare("SELECT * FROM story_blocks WHERE story_id=? ORDER BY sort_order ASC").bind(id).all(); return Response.json({ success: true, blocks: result.results }); } catch (error) { console.error(error); return Response.json({ success: false, error: "Failed to reorder story blocks" }, { status: 500 }); } }
