"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Destination={id:string;name:string};
type Category={id:string;name:string;slug:string};
type Location={id:string;name:string;slug:string;city:string|null;country:string|null};
type CategoryResponse={categories?:Category[]};
type LocationResponse={locations?:Location[]};

function makeSlug(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/đ/g,"d").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")}

export default function NewStoryPage(){
 const[form,setForm]=useState({title:"",slug:"",date:"",description:"",destination_id:""});
 const[destinations,setDestinations]=useState<Destination[]>([]);const[categories,setCategories]=useState<Category[]>([]);const[locations,setLocations]=useState<Location[]>([]);
 const[selectedCategories,setSelectedCategories]=useState<Category[]>([]);const[selectedLocations,setSelectedLocations]=useState<Location[]>([]);
 const[categoryInput,setCategoryInput]=useState("");const[locationInput,setLocationInput]=useState("");
 const[saving,setSaving]=useState(false);const[creatingCategory,setCreatingCategory]=useState(false);const[creatingLocation,setCreatingLocation]=useState(false);const[error,setError]=useState("");
 const[slugStatus,setSlugStatus]=useState<"idle"|"checking"|"available"|"taken">("idle");

 useEffect(()=>{async function loadOptions(){try{const[destinationResponse,categoryResponse,locationResponse]=await Promise.all([fetch("/api/admin/destinations",{cache:"no-store"}),fetch("/api/admin/story-categories",{cache:"no-store"}),fetch("/api/admin/locations",{cache:"no-store"})]);const destinationData=await destinationResponse.json() as {destinations?:Destination[]};const categoryData=await categoryResponse.json() as CategoryResponse;const locationData=await locationResponse.json() as LocationResponse;setDestinations(destinationData.destinations??[]);setCategories(categoryData.categories??[]);setLocations(locationData.locations??[])}catch{setDestinations([]);setCategories([]);setLocations([])}}void loadOptions()},[]);

 useEffect(()=>{const slug=form.slug.trim();if(!slug){setSlugStatus("idle");return}setSlugStatus("checking");const controller=new AbortController();const timer=window.setTimeout(async()=>{try{const response=await fetch(`/api/admin/stories?slug=${encodeURIComponent(slug)}`,{cache:"no-store",signal:controller.signal});const data=await response.json() as {success?:boolean;available?:boolean};setSlugStatus(data.success&&data.available?"available":"taken")}catch(error){if((error as Error).name!=="AbortError")setSlugStatus("idle")}},350);return()=>{window.clearTimeout(timer);controller.abort()}},[form.slug]);

 const filteredCategories=useMemo(()=>{const q=categoryInput.trim().toLowerCase();return categories.filter(c=>!selectedCategories.some(x=>x.id===c.id)).filter(c=>!q||c.name.toLowerCase().includes(q)).slice(0,8)},[categories,categoryInput,selectedCategories]);
 const filteredLocations=useMemo(()=>{const q=locationInput.trim().toLowerCase();return locations.filter(l=>!selectedLocations.some(x=>x.id===l.id)).filter(l=>!q||`${l.name} ${l.city??""} ${l.country??""}`.toLowerCase().includes(q)).slice(0,8)},[locations,locationInput,selectedLocations]);

 async function addCategory(name?:string){const value=(name??categoryInput).trim();if(!value||creatingCategory)return;const existing=categories.find(c=>c.name.toLowerCase()===value.toLowerCase());if(existing){if(!selectedCategories.some(x=>x.id===existing.id))setSelectedCategories(x=>[...x,existing]);setCategoryInput("");return}setCreatingCategory(true);setError("");try{const r=await fetch("/api/admin/story-categories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:value})});const d=await r.json() as {success?:boolean;category?:Category;error?:string};if(!r.ok||!d.success||!d.category){setError(d.error||"Could not create category.");return}setCategories(x=>x.some(i=>i.id===d.category!.id)?x:[...x,d.category!].sort((a,b)=>a.name.localeCompare(b.name)));setSelectedCategories(x=>x.some(i=>i.id===d.category!.id)?x:[...x,d.category!]);setCategoryInput("")}catch{setError("Could not create category.")}finally{setCreatingCategory(false)}}
 async function addLocation(name?:string){const value=(name??locationInput).trim();if(!value||creatingLocation)return;const existing=locations.find(l=>l.name.toLowerCase()===value.toLowerCase());if(existing){if(!selectedLocations.some(x=>x.id===existing.id))setSelectedLocations(x=>[...x,existing]);setLocationInput("");return}setCreatingLocation(true);setError("");try{const r=await fetch("/api/admin/locations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:value})});const d=await r.json() as {success?:boolean;location?:Location;error?:string};if(!r.ok||!d.success||!d.location){setError(d.error||"Could not create location.");return}setLocations(x=>x.some(i=>i.id===d.location!.id)?x:[...x,d.location!].sort((a,b)=>a.name.localeCompare(b.name)));setSelectedLocations(x=>x.some(i=>i.id===d.location!.id)?x:[...x,d.location!]);setLocationInput("")}catch{setError("Could not create location")}finally{setCreatingLocation(false)}}
 function removeCategory(id:string){setSelectedCategories(x=>x.filter(i=>i.id!==id))}function removeLocation(id:string){setSelectedLocations(x=>x.filter(i=>i.id!==id))}

 async function createStory(event:React.FormEvent){event.preventDefault();setError("");if(!form.title.trim()||!form.slug.trim()){setError("Title and slug are required.");return}if(slugStatus!=="available"){setError(slugStatus==="taken"?"This slug is already in use.":"Please wait until the slug has been checked.");return}setSaving(true);try{const r=await fetch("/api/admin/stories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:form.title.trim(),slug:form.slug.trim(),date:form.date||null,description:form.description.trim()||null,destination_id:form.destination_id||null,category_ids:selectedCategories.map(c=>c.id),location_ids:selectedLocations.map(l=>l.id)})});const d=await r.json() as {success?:boolean;story?:{id:string};error?:string};if(!r.ok||!d.success||!d.story?.id){setError(d.error||"Could not create story.");return}window.location.href=`/admin/stories/${d.story.id}`}catch{setError("Could not create story. Please try again.")}finally{setSaving(false)}}

 const slugClass=slugStatus==="taken"?"border-red-500 focus:border-red-600":slugStatus==="available"?"border-[#9bad91] focus:border-[#718568]":"border-[#d8d3ca] focus:border-[#171717]";
 return <main className="min-h-screen bg-[#f7f5f0] px-5 py-8 text-[#171717] md:px-10 md:py-12"><div className="mx-auto max-w-5xl"><Link href="/admin/stories" className="text-[11px] uppercase tracking-[0.18em] text-[#77736c]">← Stories</Link><header className="mt-10 border-b border-[#d8d3ca] pb-8"><p className="text-[11px] uppercase tracking-[0.24em] text-[#77736c]">Editorial</p><h1 className="mt-3 font-serif text-5xl md:text-6xl">New Story</h1><p className="mt-4 max-w-xl text-sm leading-6 text-[#77736c]">Create the story details first. You will build the story content and blocks in the editor after saving.</p></header>
 <form onSubmit={createStory} className="mt-10"><section className="bg-white p-6 md:p-8"><div className="grid gap-8 md:grid-cols-2">
 <label className="block"><span className="text-[10px] uppercase tracking-[0.18em] text-[#77736c]">Title *</span><input autoFocus value={form.title} onChange={e=>{const title=e.target.value;setForm(x=>({...x,title,slug:x.slug||makeSlug(title)}))}} placeholder="Anna & James" className="mt-2 h-12 w-full border border-[#d8d3ca] bg-[#fffefa] px-4 text-base outline-none focus:border-[#171717]"/></label>
 <label className="block"><span className="text-[10px] uppercase tracking-[0.18em] text-[#77736c]">Slug *</span><input value={form.slug} onChange={e=>setForm(x=>({...x,slug:makeSlug(e.target.value)}))} placeholder="anna-james-da-nang" className={`mt-2 h-12 w-full bg-[#fffefa] px-4 text-base outline-none ${slugClass}`}/>{slugStatus==="taken"&&<span className="mt-2 block text-xs font-medium text-red-600">This slug is already in use.</span>}{slugStatus==="checking"&&<span className="mt-2 block text-[11px] text-[#99958e]">Checking slug…</span>}{slugStatus==="available"&&<span className="mt-2 block text-[11px] text-[#718568]">Slug is available.</span>}<span className="mt-2 block text-[11px] text-[#99958e]">/stories/{form.slug||"your-story"}</span></label>
 <div className="md:col-span-2"><span className="text-[10px] uppercase tracking-[0.18em] text-[#77736c]">Categories</span><div className="mt-2 border border-[#d8d3ca] bg-[#fffefa] p-2"><div className="flex flex-wrap gap-2">{selectedCategories.map(c=><button key={c.id} type="button" onClick={()=>removeCategory(c.id)} className="inline-flex items-center gap-2 bg-[#ebe7df] px-3 py-2 text-xs">{c.name}<span>×</span></button>)}<input value={categoryInput} onChange={e=>setCategoryInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void addCategory()}if(e.key==="Backspace"&&!categoryInput&&selectedCategories.length)removeCategory(selectedCategories[selectedCategories.length-1].id)}} placeholder={selectedCategories.length?"Add another category…":"Type a category and press Enter…"} className="min-w-[220px] flex-1 bg-transparent px-2 py-2 text-sm outline-none"/></div>{(categoryInput||filteredCategories.length>0)&&<div className="mt-2 border-t border-[#e6e1d9] pt-2">{filteredCategories.map(c=><button key={c.id} type="button" onClick={()=>void addCategory(c.name)} className="mr-2 mb-2 border border-[#d8d3ca] px-3 py-2 text-xs">{c.name}</button>)}{categoryInput.trim()&&!categories.some(c=>c.name.toLowerCase()===categoryInput.trim().toLowerCase())&&<button type="button" onClick={()=>void addCategory()} className="mr-2 mb-2 border border-dashed border-[#aaa59c] px-3 py-2 text-xs">+ Create “{categoryInput.trim()}”</button>}</div>}</div><p className="mt-2 text-[11px] text-[#99958e]">A story can have multiple categories.</p></div>
 <label className="block"><span className="text-[10px] uppercase tracking-[0.18em] text-[#77736c]">Destination</span><select value={form.destination_id} onChange={e=>setForm(x=>({...x,destination_id:e.target.value}))} className="mt-2 h-12 w-full border border-[#d8d3ca] bg-[#fffefa] px-4 text-sm outline-none"><option value="">Select destination</option>{destinations.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>
 <div><span className="text-[10px] uppercase tracking-[0.18em] text-[#77736c]">Locations</span><div className="mt-2 border border-[#d8d3ca] bg-[#fffefa] p-2"><div className="flex flex-wrap gap-2">{selectedLocations.map(l=><button key={l.id} type="button" onClick={()=>removeLocation(l.id)} className="inline-flex items-center gap-2 bg-[#ebe7df] px-3 py-2 text-xs">{l.name}<span>×</span></button>)}<input value={locationInput} onChange={e=>setLocationInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void addLocation()}if(e.key==="Backspace"&&!locationInput&&selectedLocations.length)removeLocation(selectedLocations[selectedLocations.length-1].id)}} placeholder={selectedLocations.length?"Add another location…":"Type a location and press Enter…"} className="min-w-[190px] flex-1 bg-transparent px-2 py-2 text-sm outline-none"/></div>{(locationInput||filteredLocations.length>0)&&<div className="mt-2 border-t border-[#e6e1d9] pt-2">{filteredLocations.map(l=><button key={l.id} type="button" onClick={()=>void addLocation(l.name)} className="mr-2 mb-2 border border-[#d8d3ca] px-3 py-2 text-xs">{l.name}{l.city?` · ${l.city}`:""}</button>)}{locationInput.trim()&&!locations.some(l=>l.name.toLowerCase()===locationInput.trim().toLowerCase())&&<button type="button" onClick={()=>void addLocation()} className="mr-2 mb-2 border border-dashed border-[#aaa59c] px-3 py-2 text-xs">+ Create “{locationInput.trim()}”</button>}</div>}</div><p className="mt-2 text-[11px] text-[#99958e]">A story can happen at multiple venues or places.</p></div>
 <label className="block"><span className="text-[10px] uppercase tracking-[0.18em] text-[#77736c]">Date</span><input type="date" value={form.date} onChange={e=>setForm(x=>({...x,date:e.target.value}))} className="mt-2 h-12 w-full border border-[#d8d3ca] bg-[#fffefa] px-4 text-sm outline-none"/></label></div>
 <label className="mt-8 block"><span className="text-[10px] uppercase tracking-[0.18em] text-[#77736c]">Description / SEO intro</span><textarea value={form.description} onChange={e=>setForm(x=>({...x,description:e.target.value}))} placeholder="A short introduction to this story..." className="mt-2 min-h-36 w-full resize-y border border-[#d8d3ca] bg-[#fffefa] px-4 py-3 text-sm leading-6 outline-none"/></label></section>
 {error&&<p className="mt-4 border border-[#e2cfcf] bg-white px-4 py-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:items-center sm:justify-between"><Link href="/admin/stories" className="px-2 py-3 text-center text-[11px] uppercase tracking-[0.16em] text-[#77736c]">Cancel</Link><button type="submit" disabled={saving||creatingCategory||creatingLocation||slugStatus!=="available"} className="bg-[#171717] px-7 py-3.5 text-[11px] uppercase tracking-[0.18em] text-white disabled:cursor-wait disabled:opacity-50">{saving?"Creating…":"Create Story →"}</button></div></form></div></main>
}
