import type { ReactNode } from "react";
import { mediaUrl } from "../../../../lib/media";

type Media = { id: string; path: string; filename?: string | null; alt?: string | null };
type Props = { variant?: string; data?: Record<string, unknown>; media?: Media[] };
function text(value: unknown) { return typeof value === "string" ? value : ""; }
function items(value: unknown) { return Array.isArray(value) ? value.map(item => item && typeof item === "object" ? item as Record<string, unknown> : {}) : []; }
function Button({ label, href, newWindow, light = false }: { label: string; href: string; newWindow?: boolean; light?: boolean }) { if (!label) return null; return <a href={href || "#"} target={newWindow ? "_blank" : undefined} rel={newWindow ? "noreferrer" : undefined} className={`inline-flex min-h-11 items-center justify-center border px-6 text-[10px] uppercase tracking-[0.18em] transition ${light ? "border-white text-white hover:bg-white hover:text-[#171717]" : "border-[#171717] hover:bg-[#171717] hover:text-white"}`}>{label}</a>; }
function Image({ src, alt = "", objectPosition = "50% 50%" }: { src?: string; alt?: string; objectPosition?: string }) { return src ? <img src={src} alt={alt} className="h-full w-full object-cover" style={{ objectPosition }} /> : <div className="h-full w-full bg-[#e8e4dc]" />; }
function contentImage(media: Media[], index = 0, thumbnail = "") { const item = media[index]; return item ? mediaUrl(item.path) : thumbnail; }
function Shell({ children }: { children: ReactNode }) { return <section className="px-6 py-14 md:px-10 md:py-20"><div className="mx-auto max-w-7xl">{children}</div></section>; }

function youtubeEmbedUrl(value: string, autoplay = false) { try { const url = new URL(value); let id = ""; if (url.hostname === "youtu.be") id = url.pathname.slice(1); if (url.hostname.includes("youtube.com")) id = url.searchParams.get("v") || url.pathname.split("/").pop() || ""; return id ? `https://www.youtube.com/embed/${id}?controls=0&loop=1&mute=1&playlist=${id}${autoplay ? "&autoplay=1" : ""}` : ""; } catch { return ""; } }
export default function ContentBlockView({ variant = "banner-1", data = {}, media = [], useThumbnailPreview = false }: Props & { useThumbnailPreview?: boolean }) {
  const thumbnail = useThumbnailPreview ? text(data.thumbnail_url) : "";
  const title = text(data.title); const body = text(data.body); const subtitle = text(data.subtitle) || body; const eyebrow = text(data.eyebrow);
  const buttonNewWindow = Boolean(data.button_new_window);
  const tint = Math.max(0, Math.min(0.7, Number(data.background_tint) || 0.25));
  const legacyBannerRatio = text(data.banner_size) === "small" || text(data.banner_size) === "medium" || text(data.banner_size) === "large" ? "16:9" : "";
  const bannerRatio = text(data.banner_ratio) || legacyBannerRatio || "16:9";
  const bannerAspectClass = bannerRatio === "3:2" ? "aspect-[3/2]" : bannerRatio === "21:9" ? "aspect-[21/9]" : "aspect-[16/9]";
  const buttonText = text(data.button_text); const buttonUrl = text(data.button_url) || "#";
  const list = items(data.items);
  if (variant === "banner-1") return <section className={`relative ${bannerAspectClass} overflow-hidden bg-[#24211e]`}>{text(data.background_type) === "video" && text(data.video_url) ? <div className="absolute inset-0 overflow-hidden bg-black"><iframe title="Banner background video" className="pointer-events-none absolute left-1/2 top-1/2 h-[180%] w-[320%] -translate-x-1/2 -translate-y-1/2 md:h-[150%] md:w-[190%]" src={youtubeEmbedUrl(text(data.video_url), true)} allow="autoplay; encrypted-media" /></div> : <Image src={contentImage(media, 0)} objectPosition={text(data.focal_point) || "50% 50%"} />}<div className="absolute inset-0 bg-black" style={{ opacity: tint }} /><div className="absolute inset-0 flex items-center justify-center px-6 text-center text-white"><div className="max-w-3xl">{eyebrow && <p className="text-[10px] uppercase tracking-[0.2em] text-white/70">{eyebrow}</p>}{title && <h2 className="mt-4 font-serif text-5xl leading-[.92] md:text-7xl">{title}</h2>}{subtitle && <p className="mx-auto mt-5 max-w-xl text-sm leading-7 text-white/80">{subtitle}</p>}<div className="mt-8"><Button label={buttonText} href={buttonUrl} newWindow={buttonNewWindow} light /></div></div></div></section>;
  if (variant === "banner-2") return <section className={`relative ${bannerAspectClass} overflow-hidden bg-[#24211e]`}>{text(data.background_type) === "video" && text(data.video_url) ? <div className="absolute inset-0 overflow-hidden bg-black"><iframe title="Banner background video" className="pointer-events-none absolute left-1/2 top-1/2 h-[180%] w-[320%] -translate-x-1/2 -translate-y-1/2 md:h-[150%] md:w-[190%]" src={youtubeEmbedUrl(text(data.video_url), true)} allow="autoplay; encrypted-media" /></div> : <Image src={contentImage(media, 0)} objectPosition={text(data.focal_point) || "50% 50%"} />}<div className="absolute inset-0 bg-black" style={{ opacity: tint }} /><div className="absolute inset-0 flex items-center justify-start px-8 text-left md:px-14 lg:px-20"><div className="max-w-2xl text-white">{eyebrow && <p className="text-[10px] uppercase tracking-[0.2em] text-white/70">{eyebrow}</p>}{title && <h2 className="mt-4 font-serif text-5xl leading-[.92] md:text-7xl">{title}</h2>}{subtitle && <p className="mt-5 max-w-xl text-sm leading-7 text-white/80">{subtitle}</p>}<div className="mt-8"><Button label={buttonText} href={buttonUrl} newWindow={buttonNewWindow} light /></div></div></div></section>;
  if (variant === "banner-3") return <Shell><div className={`grid ${bannerAspectClass} overflow-hidden bg-[#f1eee8] md:grid-cols-2`}><div className="flex items-center p-8 md:p-12 lg:p-16"><div className="max-w-xl">{eyebrow && <p className="text-[10px] uppercase tracking-[0.2em] text-[#77736c]">{eyebrow}</p>}{title && <h2 className="mt-4 font-serif text-5xl leading-[.94] md:text-7xl">{title}</h2>}{subtitle && <p className="mt-5 text-sm leading-7 text-[#77736c]">{subtitle}</p>}<div className="mt-8"><Button label={buttonText} href={buttonUrl} newWindow={buttonNewWindow} /></div></div></div><div className="min-h-[280px] md:min-h-full"><Image src={contentImage(media, 0)} objectPosition={text(data.focal_point) || "50% 50%"} /></div></div></Shell>;
  if (variant === "info-1") return <Shell><div className="grid gap-5 md:grid-cols-3">{list.slice(0,3).map((item,index)=><article key={index} className="border-t border-[#d8d3ca] pt-5"><p className="text-[10px] uppercase tracking-[0.18em] text-[#8a857d]">{String(index+1).padStart(2,"0")}</p><h3 className="mt-4 font-serif text-3xl">{text(item.title)}</h3><p className="mt-3 text-sm leading-7 text-[#77736c]">{text(item.text)}</p></article>)}</div></Shell>;

  if (variant === "info-2") return <Shell><div className="grid gap-10 md:grid-cols-12 md:items-start"><div className="md:col-span-5">{eyebrow && <p className="text-[10px] uppercase tracking-[0.2em] text-[#77736c]">{eyebrow}</p>}{title && <h2 className="mt-4 font-serif text-5xl leading-[.92] md:text-7xl">{title}</h2>}</div><div className="md:col-span-6 md:col-start-7">{body && <p className="text-base leading-8 text-[#77736c]">{body}</p>}<div className="mt-8 space-y-5">{list.slice(0,3).map((item,index)=><div key={index} className="border-t border-[#d8d3ca] pt-5"><h3 className="font-serif text-2xl">{text(item.title)}</h3><p className="mt-2 text-sm leading-7 text-[#77736c]">{text(item.text)}</p></div>)}</div></div></div></Shell>;
  if (variant === "info-3") return <Shell><div className="border-y border-[#d8d3ca]">{list.slice(0,3).map((item,index)=><div key={index} className="grid gap-3 border-b border-[#d8d3ca] py-7 last:border-b-0 md:grid-cols-12 md:items-baseline"><span className="text-[10px] uppercase tracking-[0.18em] text-[#8a857d] md:col-span-1">{String(index+1).padStart(2,"0")}</span><h3 className="font-serif text-3xl md:col-span-4">{text(item.title)}</h3><p className="text-sm leading-7 text-[#77736c] md:col-span-6 md:col-start-7">{text(item.text)}</p></div>)}</div></Shell>;
  if (variant === "testimonial-2") return <Shell><div className="grid gap-10 bg-[#f1eee8] p-7 md:grid-cols-2 md:p-12"><div className="aspect-[4/5]"><Image src={contentImage(media, 0, thumbnail)} /></div><div className="flex items-center"><div><p className="font-serif text-4xl leading-[1.1] md:text-5xl">“{text(data.quote)}”</p><p className="mt-8 text-xs uppercase tracking-[0.16em]">{text(data.author)}</p>{text(data.role)&&<p className="mt-2 text-xs text-[#77736c]">{text(data.role)}</p>}</div></div></div></Shell>;
  if (variant === "testimonial-3") return <Shell><div className="mx-auto max-w-4xl border border-[#d8d3ca] bg-white p-8 text-center md:p-14"><p className="font-serif text-4xl leading-[1.08] md:text-6xl">“{text(data.quote)}”</p><div className="mt-8 text-[10px] uppercase tracking-[0.18em]">{text(data.author)}</div>{text(data.role)&&<div className="mt-2 text-xs text-[#77736c]">{text(data.role)}</div>}</div></Shell>;
  if (variant.startsWith("testimonial")) return <Shell><div className="mx-auto max-w-3xl text-center"><p className="text-[10px] uppercase tracking-[0.2em] text-[#77736c]">Testimonial</p><p className="mt-6 font-serif text-4xl leading-[1.08] md:text-6xl">“{text(data.quote)}”</p><p className="mt-8 text-xs uppercase tracking-[0.18em]">{text(data.author)}</p>{text(data.role)&&<p className="mt-2 text-xs text-[#77736c]">{text(data.role)}</p>}</div></Shell>;
  if (variant === "pricing-2") return <Shell><div className="grid gap-px overflow-hidden border border-[#d8d3ca] bg-[#d8d3ca] md:grid-cols-3">{list.slice(0,3).map((item,index)=><article key={index} className="bg-white p-7 md:p-9"><h3 className="font-serif text-3xl">{text(item.title)}</h3><p className="mt-3 text-4xl">{text(item.price)}</p><p className="mt-4 text-sm leading-7 text-[#77736c]">{text(item.text)}</p><ul className="mt-7 space-y-2 text-xs text-[#77736c]">{String(item.features ?? "").split(",").filter(Boolean).map((feature,i)=><li key={i}>— {feature.trim()}</li>)}</ul></article>)}</div></Shell>;
  if (variant === "pricing-3") return <Shell><div className="mx-auto max-w-5xl">{list.slice(0,3).map((item,index)=><article key={index} className="grid gap-3 border-b border-[#d8d3ca] py-7 md:grid-cols-12 md:items-start"><h3 className="font-serif text-3xl md:col-span-4">{text(item.title)}</h3><p className="font-serif text-3xl md:col-span-2">{text(item.price)}</p><div className="text-sm leading-7 text-[#77736c] md:col-span-5 md:col-start-8"><p>{text(item.text)}</p><p className="mt-3 text-xs">{text(item.features)}</p></div></article>)}</div></Shell>;

  if (variant.startsWith("pricing")) return <Shell><div className="grid gap-5 md:grid-cols-3">{list.slice(0,3).map((item,index)=><article key={index} className="border border-[#d8d3ca] p-7 md:p-9"><p className="text-[10px] uppercase tracking-[0.18em] text-[#77736c]">{text(item.title)}</p><p className="mt-5 font-serif text-5xl">{text(item.price)}</p><p className="mt-4 text-sm leading-7 text-[#77736c]">{text(item.text)}</p><ul className="mt-7 space-y-2 text-xs leading-5 text-[#77736c]">{String(item.features ?? "").split(",").filter(Boolean).map((feature,i)=><li key={i}>— {feature.trim()}</li>)}</ul></article>)}</div></Shell>;
  if (variant === "faq-2") return <Shell><div className="grid gap-6 md:grid-cols-2">{list.map((item,index)=><details key={index} className="border-t border-[#d8d3ca] py-5"><summary className="cursor-pointer list-none font-serif text-2xl">{text(item.question)}</summary><p className="mt-3 max-w-xl text-sm leading-7 text-[#77736c]">{text(item.answer)}</p></details>)}</div></Shell>;
  if (variant === "faq-3") return <Shell><div className="mx-auto max-w-4xl">{list.map((item,index)=><details key={index} className="border-b border-[#d8d3ca] py-5"><summary className="flex cursor-pointer list-none items-start gap-5 font-serif text-2xl"><span className="font-sans text-[10px] uppercase tracking-[0.16em] text-[#8a857d]">{String(index+1).padStart(2,"0")}</span>{text(item.question)}</summary><p className="mt-3 pl-9 text-sm leading-7 text-[#77736c]">{text(item.answer)}</p></details>)}</div></Shell>;
  if (variant.startsWith("faq")) return <Shell><div className="mx-auto max-w-3xl">{title && <h2 className="font-serif text-5xl">{title}</h2>}{list.map((item,index)=><details key={index} className="border-b border-[#d8d3ca] py-5"><summary className="cursor-pointer list-none font-serif text-2xl">{text(item.question)}</summary><p className="mt-3 text-sm leading-7 text-[#77736c]">{text(item.answer)}</p></details>)}</div></Shell>;
  if (variant === "quote-2") return <Shell><div className="border-l-2 border-[#171717] pl-7 md:pl-12"><p className="max-w-4xl font-serif text-5xl leading-[.98] md:text-7xl">“{text(data.quote)}”</p><div className="mt-7 text-[10px] uppercase tracking-[0.18em]">{text(data.author)}</div></div></Shell>;
  if (variant === "quote-3") return <section className="bg-[#171717] px-6 py-20 text-[#f7f5f0] md:px-10 md:py-28"><div className="mx-auto max-w-5xl"><p className="font-serif text-5xl leading-[.98] md:text-7xl">“{text(data.quote)}”</p><div className="mt-8 text-[10px] uppercase tracking-[0.18em] text-white/60">{text(data.author)}</div></div></section>;
  if (variant.startsWith("quote")) return <Shell><div className="mx-auto max-w-4xl text-center"><p className="font-serif text-5xl leading-[1] md:text-7xl">“{text(data.quote)}”</p><div className="mt-8 text-[10px] uppercase tracking-[0.18em] text-[#77736c]">{text(data.author)}</div></div></Shell>;
  if (variant === "banner-1") { const hasBackground = Boolean(media[0] || thumbnail); return <section className={`relative overflow-hidden ${bannerAspectClass} ${hasBackground ? "bg-[#24211e] text-white" : "bg-[#efede8] text-[#171717]"} px-6 text-center md:px-10`}>{hasBackground && <><Image src={contentImage(media, 0, thumbnail)} /><div className="absolute inset-0 bg-black" style={{ opacity: tint }} /></>}<div className="relative z-10 flex h-full min-h-full items-center justify-center py-16 md:py-24"><div className="mx-auto max-w-4xl">{eyebrow && <p className={`text-[10px] uppercase tracking-[0.2em] ${hasBackground ? "text-white/70" : "text-[#77736c]"}`}>{eyebrow}</p>}{title && <h2 className="mt-4 font-serif text-5xl leading-[.92] md:text-7xl">{title}</h2>}{subtitle && <p className={`mx-auto mt-5 max-w-xl text-sm leading-7 ${hasBackground ? "text-white/80" : "text-[#77736c]"}`}>{subtitle}</p>}<div className="mt-8"><Button label={buttonText} href={buttonUrl} newWindow={buttonNewWindow} light={hasBackground} /></div></div></div></section>; }
  return <Shell><div className="grid gap-6 md:grid-cols-2 md:items-end"><div><p className="text-[10px] uppercase tracking-[0.18em] text-[#77736c]">{eyebrow || "Content"}</p><h2 className="mt-3 font-serif text-4xl">{title || "Enter a Heading"}</h2></div><div><p className="text-sm leading-7 text-[#77736c]">{subtitle || "Add content to this block."}</p><div className="mt-6"><Button label={buttonText} href={buttonUrl} newWindow={buttonNewWindow} /></div></div></div></Shell>;
}