"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Page = { id: string; title: string; slug: string; page_type: string; seo_title?: string | null; seo_description?: string | null };
type Block = { id: string; type: string; data: Record<string, unknown> };
type PagesResponse = { pages?: Page[] };
type PageBlocksResponse = { blocks?: Array<{ id: string; type: string; data: string | Record<string, unknown> }> };
const BLOCKS = ["text", "image", "content", "links", "blog", "video", "contact", "social", "others", "flex"];

function parse(value: string | Record<string, unknown>) { if (typeof value !== "string") return value; try { return JSON.parse(value) as Record<string, unknown>; } catch { return {}; } }
function setValue(data: Record<string, unknown>, key: string, value: string) { return { ...data, [key]: value }; }

export default function AdminPagesPage() {
  const [pages, setPages] = useState<Page[]>([]); const [page, setPage] = useState<Page | null>(null); const [blocks, setBlocks] = useState<Block[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  async function load() { const response=await fetch("/api/admin/pages",{cache:"no-store"}); const data=(await response.json()) as PagesResponse; setPages(data.pages??[]); setLoading(false); }
  useEffect(()=>{load();},[]);
  async function openPage(item: Page) { setPage(item); const response=await fetch(`/api/pages/${item.slug}`,{cache:"no-store"}); const data=(await response.json()) as PageBlocksResponse; setBlocks((data.blocks??[]).map(b=>({id:b.id,type:b.type,data:parse(b.data)}))); }
  function addBlock(type:string){setBlocks(prev=>[...prev,{id:crypto.randomUUID(),type,data:{}}]);}
  function move(index:number,direction:-1|1){const next=[...blocks];const target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setBlocks(next);}
  function remove(id:string){setBlocks(prev=>prev.filter(b=>b.id!==id));}
  async function save(){if(!page)return;setMessage("");const response=await fetch("/api/admin/pages",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:page.id,title:page.title,seo_title:page.seo_title,seo_description:page.seo_description,blocks})});const data=(await response.json()) as {success:boolean;error?:string};setMessage(response.ok&&data.success?"Saved.":data.error||"Could not save.");}
  if(loading)return <main className="p-12">Loading…</main>;
  if(!page)return <main className="min-h-screen bg-[#f7f5f0] px-6 py-12"><div className="mx-auto max-w-5xl"><Link href="/admin" className="text-xs uppercase tracking-[0.16em] text-[#77736c]">← Admin</Link><h1 className="mt-8 font-serif text-5xl">Pages</h1><p className="mt-3 text-sm text-[#77736c]">Home and About are editable with the same block philosophy as Stories.</p><div className="mt-10 grid gap-4 md:grid-cols-2">{pages.map(item=><button key={item.id} onClick={()=>openPage(item)} className="border border-[#d8d3ca] bg-white p-6 text-left hover:-translate-y-0.5"><p className="text-[10px] uppercase tracking-[0.18em] text-[#77736c]">{item.page_type}</p><h2 className="mt-3 font-serif text-3xl">{item.title}</h2><p className="mt-2 text-xs text-[#77736c]">/{item.slug}</p></button>)}</div></div></main>;
  return <main className="min-h-screen bg-[#f7f5f0] px-6 py-10"><div className="mx-auto max-w-5xl"><button onClick={()=>setPage(null)} className="text-xs uppercase tracking-[0.16em] text-[#77736c]">← Pages</button><div className="mt-7 flex flex-wrap items-end justify-between gap-6"><div><p className="text-xs uppercase tracking-[0.2em] text-[#77736c]">Page Builder</p><h1 className="mt-3 font-serif text-5xl">{page.title}</h1><p className="mt-2 text-sm text-[#77736c]">/{page.slug}</p></div><button onClick={save} className="bg-[#171717] px-5 py-3 text-xs uppercase tracking-[0.15em] text-white">Save Page</button></div>{message&&<p className="mt-5 text-sm text-[#77736c]">{message}</p>}
  <section className="mt-10 border border-[#d8d3ca] bg-white p-6"><h2 className="font-serif text-2xl">SEO</h2><div className="mt-5 grid gap-4"><input className="border p-3" placeholder="SEO title" value={page.seo_title??""} onChange={e=>setPage({...page,seo_title:e.target.value})}/><textarea className="min-h-20 border p-3" placeholder="SEO description" value={page.seo_description??""} onChange={e=>setPage({...page,seo_description:e.target.value})}/></div></section>
  <section className="mt-10"><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="font-serif text-3xl">Add Block</h2><div className="flex flex-wrap gap-2">{BLOCKS.map(type=><button key={type} onClick={()=>addBlock(type)} className="border border-[#d8d3ca] bg-white px-3 py-2 text-[10px] uppercase tracking-[0.12em]">{type}</button>)}</div></div><div className="mt-6 grid gap-4">{blocks.map((block,index)=>{const data=block.data;return <article key={block.id} className="border border-[#d8d3ca] bg-white p-5"><div className="flex items-center justify-between gap-4"><div><span className="text-[10px] uppercase tracking-[0.16em] text-[#77736c]">Block {index+1}</span><h3 className="mt-1 font-serif text-2xl">{block.type}</h3></div><div className="flex gap-2"><button onClick={()=>move(index,-1)} className="border px-3 py-1">↑</button><button onClick={()=>move(index,1)} className="border px-3 py-1">↓</button><button onClick={()=>remove(block.id)} className="border px-3 py-1">×</button></div></div><div className="mt-5 grid gap-3"><input className="border p-3" placeholder="Eyebrow / label" value={String(data.eyebrow??"")} onChange={e=>setBlocks(prev=>prev.map(b=>b.id===block.id?{...b,data:setValue(b.data,"eyebrow",e.target.value)}:b))}/><input className="border p-3" placeholder="Title" value={String(data.title??"")} onChange={e=>setBlocks(prev=>prev.map(b=>b.id===block.id?{...b,data:setValue(b.data,"title",e.target.value)}:b))}/><textarea className="min-h-28 border p-3" placeholder="Body / text" value={String(data.body??"")} onChange={e=>setBlocks(prev=>prev.map(b=>b.id===block.id?{...b,data:setValue(b.data,"body",e.target.value)}:b))}/>{["image","flex"].includes(block.type)&&<input className="border p-3" placeholder="Image URL or media path" value={String(data.image_url??"")} onChange={e=>setBlocks(prev=>prev.map(b=>b.id===block.id?{...b,data:setValue(b.data,"image_url",e.target.value)}:b))}/>} {["video","contact"].includes(block.type)&&<input className="border p-3" placeholder="URL" value={String(data.url??"")} onChange={e=>setBlocks(prev=>prev.map(b=>b.id===block.id?{...b,data:setValue(b.data,"url",e.target.value)}:b))}/>} {block.type==="image"&&<input className="border p-3" placeholder="Alt text" value={String(data.alt??"")} onChange={e=>setBlocks(prev=>prev.map(b=>b.id===block.id?{...b,data:setValue(b.data,"alt",e.target.value)}:b))}/>} </div></article>})}</div></section></div></main>;
}
