"use client";

import { useEffect, useRef, useState } from "react";
import AddBlockTrigger from "../AddBlockTrigger";
import { mediaUrl } from "@/lib/media";
import type { StoryBlock } from "./types";

type Props = { storyId: string; blocks: StoryBlock[]; onBlocksChange: (blocks: StoryBlock[]) => void; onDelete: (blockId: string) => void; onUpdate: (block: StoryBlock, patch: Partial<StoryBlock>) => void };
const TEXT_LABELS: Record<string, string> = { "heading-1": "Heading 1", "heading-2": "Heading 2", "heading-3": "Heading 3", wide: "Wide Text", regular: "Regular Text", narrow: "Narrow Text", "columns-2": "Text Columns 2", "columns-3": "Text Columns 3", "columns-4": "Text Columns 4", "text-h1": "Heading 1", "text-h2": "Heading 2", "text-h3": "Heading 3", "text-wide": "Wide Text", "text-regular": "Regular Text", "text-narrow": "Narrow Text", "text-columns-2": "Text Columns 2", "text-columns-3": "Text Columns 3", "text-columns-4": "Text Columns 4" };
const TEXT_STYLES: Record<string, string> = { "heading-1": "text-5xl font-serif leading-[1.08]", "text-h1": "text-5xl font-serif leading-[1.08]", "heading-2": "text-4xl font-serif leading-[1.12]", "text-h2": "text-4xl font-serif leading-[1.12]", "heading-3": "text-3xl font-serif leading-[1.16]", "text-h3": "text-3xl font-serif leading-[1.16]", wide: "text-xl leading-8", "text-wide": "text-xl leading-8", regular: "text-base leading-7", "text-regular": "text-base leading-7", narrow: "mx-auto max-w-2xl text-base leading-7", "text-narrow": "mx-auto max-w-2xl text-base leading-7", "columns-2": "text-base leading-7", "text-columns-2": "text-base leading-7", "columns-3": "text-base leading-7", "text-columns-3": "text-base leading-7", "columns-4": "text-base leading-7", "text-columns-4": "text-base leading-7" };
const ALIGNMENTS = [{ command: "justifyLeft", icon: "☰", title: "Align left" }, { command: "justifyCenter", icon: "≡", title: "Align center" }, { command: "justifyRight", icon: "☰", title: "Align right" }, { command: "justifyFull", icon: "☷", title: "Justify" }] as const;
const FONT_SIZES = [8, 10, 12, 14, 16, 18, 20, 24, 28, 32, 36, 42, 48, 56, 64, 72];

function TextToolbar({ editorRef, onChange }: { editorRef: React.RefObject<HTMLDivElement | null>; onChange: () => void }) {
  const run = (command: string, value?: string) => { editorRef.current?.focus(); document.execCommand(command, false, value); onChange(); };
  const setFontSize = (size: number) => { editorRef.current?.focus(); document.execCommand("fontSize", false, "7"); const fontTags = editorRef.current?.querySelectorAll('font[size="7"]'); fontTags?.forEach(node => { const el = node as HTMLElement; el.removeAttribute("size"); el.style.fontSize = `${size}px`; }); onChange(); };
  return <div className="flex flex-wrap items-center gap-0.5 border-b border-[#d9d3ca] bg-[#f7f4ef] px-2 py-1.5 shadow-sm">
    <select aria-label="Font size" title="Font size" defaultValue="16" onChange={e => setFontSize(Number(e.target.value))} className="h-8 w-[72px] border border-[#d9d3ca] bg-white px-2 text-xs outline-none hover:border-[#aaa49a]">{FONT_SIZES.map(size => <option key={size} value={size}>{size}px</option>)}</select>
    <span className="mx-1 h-5 w-px bg-[#d9d3ca]" />
    <button type="button" title="Bold" aria-label="Bold" onMouseDown={e => e.preventDefault()} onClick={() => run("bold")} className="flex h-8 w-8 items-center justify-center rounded-sm text-sm font-bold hover:bg-white">B</button>
    <button type="button" title="Italic" aria-label="Italic" onMouseDown={e => e.preventDefault()} onClick={() => run("italic")} className="flex h-8 w-8 items-center justify-center rounded-sm text-sm italic hover:bg-white">I</button>
    <button type="button" title="Underline" aria-label="Underline" onMouseDown={e => e.preventDefault()} onClick={() => run("underline")} className="flex h-8 w-8 items-center justify-center rounded-sm text-sm underline hover:bg-white">U</button>
    <label title="Text color" className="relative flex h-8 w-8 cursor-pointer items-center justify-center rounded-sm hover:bg-white"><span className="relative text-sm font-semibold after:absolute after:bottom-0 after:left-0 after:right-0 after:h-0.5 after:bg-black">A</span><input aria-label="Text color" type="color" className="absolute inset-0 cursor-pointer opacity-0" onChange={e => run("foreColor", e.target.value)} /></label>
    <span className="mx-1 h-5 w-px bg-[#d9d3ca]" />
    {ALIGNMENTS.map(({ command, icon, title }, index) => <button key={command} type="button" title={title} aria-label={title} onMouseDown={e => e.preventDefault()} onClick={() => run(command)} className="flex h-8 w-8 items-center justify-center rounded-sm text-sm hover:bg-white"><span className={index === 0 ? "text-left" : index === 1 ? "text-center" : index === 2 ? "text-right" : "text-justify"}>{icon}</span></button>)}
    <span className="mx-1 h-5 w-px bg-[#d9d3ca]" />
    <button type="button" title="Bulleted list" aria-label="Bulleted list" onMouseDown={e => e.preventDefault()} onClick={() => run("insertUnorderedList")} className="flex h-8 w-8 items-center justify-center rounded-sm text-sm hover:bg-white">•☰</button>
    <button type="button" title="Numbered list" aria-label="Numbered list" onMouseDown={e => e.preventDefault()} onClick={() => run("insertOrderedList")} className="flex h-8 w-8 items-center justify-center rounded-sm text-xs hover:bg-white">1☰</button>
    <button type="button" title="Clear formatting" aria-label="Clear formatting" onMouseDown={e => e.preventDefault()} onClick={() => run("removeFormat")} className="flex h-8 w-8 items-center justify-center rounded-sm text-sm font-medium hover:bg-white">T<span className="text-[#77736c]">x</span></button>
  </div>;
}

function TextBlockEditor({ block, onChange, onBlur }: { block: StoryBlock; onChange: (patch: Partial<StoryBlock>) => void; onBlur: () => void }) { const editorRef = useRef<HTMLDivElement | null>(null); const [editing, setEditing] = useState(false); const content = block.body ?? block.title ?? ""; useEffect(() => { if (editorRef.current && !editing && editorRef.current.innerHTML !== content) editorRef.current.innerHTML = content; }, [content, editing]); const changed = () => onChange({ body: editorRef.current?.innerHTML ?? "" }); const variant = block.variant ?? block.type; const style = TEXT_STYLES[variant] ?? "text-base leading-7"; const isColumns = variant.includes("columns-2") || variant.includes("columns-3") || variant.includes("columns-4"); const columns = variant.includes("columns-4") ? 4 : variant.includes("columns-3") ? 3 : 2; return <div className="overflow-hidden border border-transparent transition-colors focus-within:border-[#d9d3ca]">{editing && <TextToolbar editorRef={editorRef} onChange={changed} />}<div className={isColumns ? "grid gap-8 " + (columns === 4 ? "md:grid-cols-4" : columns === 3 ? "md:grid-cols-3" : "md:grid-cols-2") : ""}><div ref={editorRef} contentEditable suppressContentEditableWarning spellCheck className={`min-h-12 whitespace-pre-wrap px-2 py-2 outline-none ${style}`} onFocus={() => setEditing(true)} onInput={changed} onBlur={() => { setEditing(false); onBlur(); }} /></div></div>; }
function BlockCard({ block, blocks, onBlocksChange, onDelete, onUpdate }: { block: StoryBlock; blocks: StoryBlock[]; onBlocksChange: Props["onBlocksChange"]; onDelete: Props["onDelete"]; onUpdate: Props["onUpdate"] }) { const textLabel = TEXT_LABELS[block.variant ?? block.type]; const isText = block.type === "text" || block.type.startsWith("text-"); const updateLocal = (patch: Partial<StoryBlock>) => onBlocksChange(blocks.map(item => item.id === block.id ? { ...item, ...patch } : item)); return <article className="group relative">{isText ? <TextBlockEditor block={block} onChange={updateLocal} onBlur={() => onUpdate(block, { body: block.body, title: block.title })} /> : <div className="border border-[#d9d3ca] bg-white p-7 lg:p-9"><p className="text-sm text-[#77736c]">This block has its own dedicated editor component.</p>{block.media.length > 0 && <div className="mt-5 grid grid-cols-3 gap-3">{block.media.map(media => <div key={media.id} className="aspect-square overflow-hidden bg-[#e7e2da]"><img src={mediaUrl(media.path)} alt={media.alt ?? media.filename} className="h-full w-full object-cover" /></div>)}</div>}</div>}<div className="absolute -top-3 right-0 z-10 flex items-center gap-2 opacity-0 transition-opacity group-hover:opacity-100 focus-within:opacity-100"><span className="bg-[#f5f2ec] px-2 py-1 text-[9px] uppercase tracking-[0.16em] text-[#8a857d]">{textLabel ?? block.variant ?? block.type}</span><button type="button" onClick={() => onDelete(block.id)} className="bg-[#f5f2ec] px-2 py-1 text-[9px] uppercase tracking-[0.15em] text-[#9a4c42] hover:text-[#6f2820]">Delete</button></div></article>; }
export default function StoryContent({ storyId, blocks, onBlocksChange, onDelete, onUpdate }: Props) { const visibleBlocks = blocks.filter(block => block.is_visible !== 0).slice().sort((a, b) => a.sort_order - b.sort_order); return <section className="min-w-0"><div className="space-y-1">{visibleBlocks.map(block => <div key={block.id}><BlockCard block={block} blocks={blocks} onBlocksChange={onBlocksChange} onDelete={onDelete} onUpdate={onUpdate}/><AddBlockTrigger storyId={storyId}/></div>)}{visibleBlocks.length === 0 && <AddBlockTrigger storyId={storyId}/>}</div></section>; }
