"use client";

import { useEffect, useRef, useState } from "react";
import AddBlockTrigger from "../AddBlockTrigger";
import TextColumnsEditor from "./TextColumnsEditor";
import ImageBlockEditor from "../blocks/image/ImageBlockEditor";
import GridGalleryEditor from "../blocks/gallery/GridGalleryEditor";
import BannerBlockEditor from "../blocks/banner/BannerBlockEditor";
import type { StoryBlock } from "./types";

type Props={storyId:string;blocks:StoryBlock[];onBlocksChange:(blocks:StoryBlock[])=>void;onDelete:(blockId:string)=>void;onUpdate:(block:StoryBlock,patch:Partial<StoryBlock>)=>void};
type DropPosition={targetId:string;side:"before"|"after"};
type SavedSelection={range:Range;editor:HTMLDivElement};

const TEXT_STYLES:Record<string,string>={"heading-1":"text-5xl font-serif leading-[1.08]","text-h1":"text-5xl font-serif leading-[1.08]","heading-2":"text-4xl font-serif leading-[1.12]","text-h2":"text-4xl font-serif leading-[1.12]","heading-3":"text-3xl font-serif leading-[1.16]","text-h3":"text-3xl font-serif leading-[1.16]",wide:"text-xl leading-8","text-wide":"text-xl leading-8",regular:"text-base leading-7","text-regular":"text-base leading-7",narrow:"mx-auto max-w-2xl text-base leading-7","text-narrow":"mx-auto max-w-2xl text-base leading-7"};
const LABELS:Record<string,string>={"heading-1":"Heading 1","heading-2":"Heading 2","heading-3":"Heading 3",wide:"Wide Text",regular:"Regular Text",narrow:"Narrow Text","text-h1":"Heading 1","text-h2":"Heading 2","text-h3":"Heading 3","text-wide":"Wide Text","text-regular":"Regular Text","text-narrow":"Narrow Text","text-columns-2":"Text Columns 2","text-columns-3":"Text Columns 3","text-columns-4":"Text Columns 4",large:"Large Image",medium:"Medium Image","full-width":"Full Width Image","columns-2":"Image Columns 2","columns-3":"Image Columns 3","columns-4":"Image Columns 4","grid-vertical":"Vertical Grid","grid-horizontal":"Horizontal Grid","grid-square":"Square Grid","grid-stacked":"Stacked Grid","banner-1":"Banner 1","banner-2":"Banner 2","banner-3":"Banner 3","banner-headline":"Banner with Headline","banner-media":"Banner Media Only","banner-slider":"Banner Slider"};

function TextBlockEditor({block,onChange,onBlur}:{block:StoryBlock;onChange:(patch:Partial<StoryBlock>)=>void;onBlur:()=>void}){const editorRef=useRef<HTMLDivElement|null>(null);const wrapperRef=useRef<HTMLDivElement|null>(null);const selectionRef=useRef<SavedSelection|null>(null);const [editing,setEditing]=useState(false);const content=block.body??block.title??"";const variant=block.variant??block.type;const style=TEXT_STYLES[variant]??"text-base leading-7";useEffect(()=>{if(editorRef.current&&!editing&&editorRef.current.innerHTML!==content)editorRef.current.innerHTML=content},[content,editing]);const saveSelection=()=>{const e=editorRef.current,s=window.getSelection();if(e&&s&&s.rangeCount&&e.contains(s.anchorNode))selectionRef.current={range:s.getRangeAt(0).cloneRange(),editor:e}};const changed=()=>{saveSelection();onChange({body:editorRef.current?.innerHTML??""})};return <div ref={wrapperRef} className="overflow-visible border border-transparent focus-within:border-[#d9d3ca]" onFocusCapture={()=>setEditing(true)} onBlurCapture={e=>{if(!wrapperRef.current?.contains(e.relatedTarget as Node|null)){setEditing(false);onBlur()}}}>{editing&&<div className="flex items-center gap-1 border-b border-[#d9d3ca] bg-[#f7f4ef] px-2 py-1.5" onMouseDown={e=>e.stopPropagation()}>{[["bold","B"],["italic","I"],["underline","U"]].map(([cmd,label])=><button key={cmd} type="button" onMouseDown={e=>{e.preventDefault();saveSelection();const saved=selectionRef.current,ed=editorRef.current;if(saved&&ed){ed.focus();const s=window.getSelection();s?.removeAllRanges();s?.addRange(saved.range);document.execCommand(cmd,false);changed()}}} className={`flex h-8 w-8 items-center justify-center text-sm hover:bg-white ${cmd==="bold"?"font-bold":cmd==="italic"?"italic":"underline"}`}>{label}</button>)}<span className="mx-1 h-5 w-px bg-[#d9d3ca]"/>{[["justifyLeft","←"],["justifyCenter","↔"],["justifyRight","→"]].map(([cmd,label])=><button key={cmd} type="button" onMouseDown={e=>{e.preventDefault();saveSelection();const saved=selectionRef.current,ed=editorRef.current;if(saved&&ed){ed.focus();const s=window.getSelection();s?.removeAllRanges();s?.addRange(saved.range);document.execCommand(cmd,false);changed()}}} className="flex h-8 w-8 items-center justify-center text-sm hover:bg-white">{label}</button>)}</div>}<div ref={editorRef} contentEditable suppressContentEditableWarning spellCheck className={`min-h-12 whitespace-pre-wrap px-2 py-2 outline-none ${style}`} onFocus={saveSelection} onKeyUp={saveSelection} onMouseUp={saveSelection} onInput={changed}/></div>}

function DragHandle({onDragStart,onDragEnd}:{onDragStart:()=>void;onDragEnd:()=>void}){return <button type="button" draggable aria-label="Drag to reorder block" title="Drag to reorder" onDragStart={e=>{e.dataTransfer.effectAllowed="move";onDragStart()}} onDragEnd={onDragEnd} className="flex h-7 w-7 cursor-grab items-center justify-center bg-[#f5f2ec] text-[#77736c] hover:bg-white active:cursor-grabbing" onMouseDown={e=>e.stopPropagation()}><svg aria-hidden="true" width="14" height="16" viewBox="0 0 14 16" fill="none"><circle cx="4" cy="3" r="1" fill="currentColor"/><circle cx="10" cy="3" r="1" fill="currentColor"/><circle cx="4" cy="8" r="1" fill="currentColor"/><circle cx="10" cy="8" r="1" fill="currentColor"/><circle cx="4" cy="13" r="1" fill="currentColor"/><circle cx="10" cy="13" r="1" fill="currentColor"/></svg></button>}

function BlockEditor({storyId,block,blocks,onBlocksChange,onUpdate}:{storyId:string;block:StoryBlock;blocks:StoryBlock[];onBlocksChange:Props["onBlocksChange"];onUpdate:Props["onUpdate"]}){const updateLocal=(patch:Partial<StoryBlock>)=>onBlocksChange(blocks.map(item=>item.id===block.id?{...item,...patch}:item));const variant=block.variant??"";const isText=block.type==="text"||block.type.startsWith("text-");const isTextColumns=isText&&["columns-2","columns-3","columns-4","text-columns-2","text-columns-3","text-columns-4"].includes(variant);const isGrid=block.type==="image"&&variant.startsWith("grid-");const isBanner=(block.type==="content"||block.type==="banner")&&variant.startsWith("banner-");if(isTextColumns)return <TextColumnsEditor block={block} onChange={updateLocal}/>;if(isText)return <TextBlockEditor block={block} onChange={updateLocal} onBlur={()=>onUpdate(block,{body:block.body,title:block.title})}/>;if(isGrid)return <GridGalleryEditor storyId={storyId} block={block} onChange={updateLocal}/>;if(block.type==="image")return <ImageBlockEditor storyId={storyId} block={block} onChange={updateLocal}/>;if(isBanner)return <BannerBlockEditor block={block} onChange={updateLocal}/>;return <div className="border border-dashed border-[#d9d3ca] bg-white p-7 lg:p-9"><p className="text-sm text-[#77736c]">This block type does not have an editor yet.</p></div>}

function BlockCard({storyId,block,blocks,onBlocksChange,onDelete,onUpdate,draggingId,onDragStart,onDragEnd,onDragOver,onDrop}:{storyId:string;block:StoryBlock;blocks:StoryBlock[];onBlocksChange:Props["onBlocksChange"];onDelete:Props["onDelete"];onUpdate:Props["onUpdate"];draggingId:string|null;onDragStart:(id:string)=>void;onDragEnd:()=>void;onDragOver:(targetId:string,side:"before"|"after")=>void;onDrop:(targetId:string,side:"before"|"after")=>void}){const variant=block.variant??block.type;return <article className="group relative" onDragOver={e=>{e.preventDefault();const r=e.currentTarget.getBoundingClientRect();onDragOver(block.id,e.clientY<r.top+r.height/2?"before":"after");e.dataTransfer.dropEffect="move"}} onDrop={e=>{e.preventDefault();const r=e.currentTarget.getBoundingClientRect();onDrop(block.id,e.clientY<r.top+r.height/2?"before":"after")}}>{draggingId===block.id&&<div className="pointer-events-none absolute inset-0 z-10 rounded-sm border-2 border-dashed border-[#8f887e] bg-[#8f887e]/5"/>}<BlockEditor storyId={storyId} block={block} blocks={blocks} onBlocksChange={onBlocksChange} onUpdate={onUpdate}/><div className="absolute -top-3 right-0 z-20 flex items-center gap-2 opacity-0 transition-opacity group-hover:opacity-100 focus-within:opacity-100"><DragHandle onDragStart={()=>onDragStart(block.id)} onDragEnd={onDragEnd}/><span className="bg-[#f5f2ec] px-2 py-1 text-[9px] uppercase tracking-[0.16em] text-[#8a857d]">{LABELS[variant]??variant}</span><button type="button" onClick={()=>onDelete(block.id)} className="bg-[#f5f2ec] px-2 py-1 text-[9px] uppercase tracking-[0.15em] text-[#9a4c42]">Delete</button></div></article>}

function DropIndicator({side,visible}:{side:"before"|"after";visible:boolean}){if(!visible)return null;return <div className={`pointer-events-none relative z-30 flex h-8 items-center ${side==="before"?"-mb-2":"-mt-2"}`}><div className="flex w-full items-center gap-3"><span className="h-2 w-2 shrink-0 rounded-full bg-[#7d4f45]"/><div className="h-0.5 flex-1 bg-[#7d4f45]"/><span className="bg-[#7d4f45] px-2 py-1 text-[9px] font-medium uppercase tracking-[0.14em] text-white">Insert block here</span><div className="h-0.5 flex-1 bg-[#7d4f45]"/><span className="h-2 w-2 shrink-0 rounded-full bg-[#7d4f45]"/></div></div>}

export default function StoryContent({storyId,blocks,onBlocksChange,onDelete,onUpdate}:Props){const visibleBlocks=blocks.filter(block=>block.is_visible!==0).slice().sort((a,b)=>a.sort_order-b.sort_order);const [draggingId,setDraggingId]=useState<string|null>(null);const [dropPosition,setDropPosition]=useState<DropPosition|null>(null);const reorderBlocks=async(targetId:string,side:"before"|"after")=>{if(!draggingId||draggingId===targetId)return;const ids=visibleBlocks.map(block=>block.id),from=ids.indexOf(draggingId);if(from<0)return;const next=[...ids];next.splice(from,1);const targetIndex=next.indexOf(targetId);if(targetIndex<0)return;next.splice(targetIndex+(side==="after"?1:0),0,draggingId);if(next.join(",")==ids.join(",")){setDraggingId(null);setDropPosition(null);return;}const previous=blocks;const ordered=next.map((id,index)=>{const b=blocks.find(item=>item.id===id);return b?{...b,sort_order:(index+1)*1000}:null}).filter((b):b is StoryBlock=>Boolean(b));const hidden=blocks.filter(b=>!ids.includes(b.id));onBlocksChange([...ordered,...hidden]);setDraggingId(null);setDropPosition(null);try{const response=await fetch(`/api/admin/stories/${storyId}/blocks`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({block_ids:next})});const data=await response.json() as {success?:boolean;blocks?:StoryBlock[];error?:string};if(!response.ok||!data.success)throw new Error(data.error??"Failed to reorder blocks");if(data.blocks)onBlocksChange(data.blocks)}catch(error){onBlocksChange(previous);console.error(error)}};return <section className="min-w-0"><div className="space-y-1">{visibleBlocks.map(block=><div key={block.id}><DropIndicator side="before" visible={dropPosition?.targetId===block.id&&dropPosition.side==="before"}/><BlockCard storyId={storyId} block={block} blocks={blocks} onBlocksChange={onBlocksChange} onDelete={onDelete} onUpdate={onUpdate} draggingId={draggingId} onDragStart={id=>setDraggingId(id)} onDragEnd={()=>{setDraggingId(null);setDropPosition(null)}} onDragOver={(targetId,side)=>setDropPosition({targetId,side})} onDrop={(targetId,side)=>void reorderBlocks(targetId,side)}/><DropIndicator side="after" visible={dropPosition?.targetId===block.id&&dropPosition.side==="after"}/><AddBlockTrigger storyId={storyId} afterBlockId={block.id}/></div>)}{visibleBlocks.length===0&&<AddBlockTrigger storyId={storyId}/>}</div></section>}
